enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
# build-mode = "apk"
build-mode = "both"
arch = "arm64-v8a"
# Stable Support #
# version = "auto" # "20.47.62"
# Experimental Support #
# version = "21.11.486" # Working Shorts BG Playback
# version = "21.16.256"
# version = "21.17.482"
version = "21.18.164"
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    'Custom branding' \
    """
# included-patches = ""
# patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor='@android:color/system_neutral1_900'"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Music-Morphe]
enabled = true
app-name = "YT Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
# build-mode = "apk"
build-mode = "both"
arch = "arm64-v8a"
# Stable Support #
# version = "auto" # "8.47.56"
# Experimental Support #
# version = "9.15.51"
# version = "9.16.51"
version = "9.17.51"
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Anddea]
enabled = false
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
# patches-source = "inotia00/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
# cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended Anddea"
version = "20.21.37"
patches-version = "dev"
build-mode = "both"
excluded-patches = " 'Enable debug logging' "
# included-patches = ""
# include-stock = true
# exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Music-Anddea]
enabled = false
app-name = "YT Music"
patches-source = "anddea/revanced-patches"
# patches-source = "inotia00/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
# cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended Anddea"
version = "auto"
arch = "arm64-v8a"
patches-version = "dev"
build-mode = "both"
excluded-patches = " 'Enable debug logging' "
included-patches = " 'Hide player overlay filter' 'Hide overlay filter' 'Disable music video in album' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
enabled = true
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
# build-mode = "apk"
build-mode = "both"
# arch = "arm64-v8a"
dpi = "120-640dpi"
# Stable Support #
# version = "auto" # "2026.10.0"
# Experimental Support #
# version = "2026.16.0"
# version = "2026.17.0"
version = "2026.18.0"
excluded-patches = """\
    'Custom branding name for Reddit' \
    'Custom branding icon for Reddit' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Google-Photos-ReVanced]
enabled = true
app-name = "Google Photos"
patches-source = "RookieEnough/De-ReVanced"
# patches-source = "ReVanced/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
# cli-source = "ReVanced/revanced-cli"
rv-brand = "De-ReVanced"
arch = "arm64-v8a"
# version = "auto"
# version = "7.68.0.888294030"
# version = "7.70.0.896053304"
version = "7.74.0.906046556"
# patches-version = "dev"
# build-mode = "apk"
build-mode = "both"
included-patches = """\
    'Enable DCIM folders backup control' \
    'Remove screenshot restriction' \
    'Remove screen capture restriction' \
    'Spoof features' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Twitter-Piko]
enabled = true
app-name = "Twitter"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
# build-mode = "apk"
build-mode = "both"
# version = "auto"
version = "11.81.0-release.0" # PairIP Free
# version = "11.85.0-release.0"
# version = "11.86.0-release.0"
include-stock = "split"
patches-version = "dev"
included-patches = """\
    'Bring back twitter' \
    'Dynamic color' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"